Repository SeniorDesignTeamFive/DegreePlanner, pull requests merged in 2018-02, with the labels that each got.

#6 arch/flx 0001 init
  deg_pln/deg_pln.sln
  deg_pln/deg_pln/db.sqlite3
  deg_pln/deg_pln/deg_pln.pyproj
  deg_pln/deg_pln/deg_pln/__init__.py
  deg_pln/deg_pln/deg_pln/settings.py
  deg_pln/deg_pln/deg_pln/urls.py
  deg_pln/deg_pln/deg_pln/wsgi.py
  deg_pln/deg_pln/manage.py
  deg_pln/deg_pln/requirements.txt
Labels: Architecture

#7 Real initial commmit. Consists of basic models for DB and views for a
  deg_pln/deg_pln.sln
  deg_pln/deg_pln/db.sqlite3
  deg_pln/deg_pln/deg_pln.pyproj
  deg_pln/deg_pln/deg_pln/settings.py
  deg_pln/deg_pln/deg_pln/urls.py
  deg_pln/deg_pln/env/.ptvs/AnalysisLog.txt
  deg_pln/deg_pln/env/Scripts/Activate.ps1
  deg_pln/deg_pln/env/Scripts/activate
  deg_pln/deg_pln/env/Scripts/django-admin.py
  deg_pln/deg_pln/env/pip-selfcheck.json
  deg_pln/deg_pln/env/pyvenv.cfg
  deg_pln/deg_pln/planner/__init__.py
  deg_pln/deg_pln/planner/admin.py
  deg_pln/deg_pln/planner/apps.py
  deg_pln/deg_pln/planner/migrations/0001_initial.py
  deg_pln/deg_pln/planner/migrations/__init__.py
  deg_pln/deg_pln/planner/models.py
  deg_pln/deg_pln/planner/templates/index.html
  deg_pln/deg_pln/planner/templates/planner/eligible.html
  deg_pln/deg_pln/planner/templates/planner/index.html
  deg_pln/deg_pln/planner/templates/planner/taken.html
  deg_pln/deg_pln/planner/tests.py
  deg_pln/deg_pln/planner/urls.py
  deg_pln/deg_pln/planner/views.py
  deg_pln/deg_pln/requirements.txt
Labels: +1 Dev, Architecture

#8 Initial DB commit. Contains All classes on CS Degree Plan.
  CS_deg.csv
  DB_load.py
  deg_pln/deg_pln/db.sqlite3
  deg_pln/deg_pln/env/.ptvs/AnalysisLog.txt
  deg_pln/deg_pln/env/pip-selfcheck.json
  deg_pln/deg_pln/planner/migrations/0002_auto_20180222_1305.py
  deg_pln/deg_pln/planner/migrations/0003_class_co_req.py
  deg_pln/deg_pln/planner/migrations/0004_auto_20180222_1329.py
  deg_pln/deg_pln/planner/migrations/0005_auto_20180222_1817.py
  deg_pln/deg_pln/planner/models.py
  deg_pln/deg_pln/planner/templates/planner/index.html
  deg_pln/deg_pln/planner/views.py
Labels: Architecture, In Review
